# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('flight', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('planetype', models.CharField(max_length=100)),
            ],
        ),
    ]
