# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=400)),
                ('gender', models.CharField(max_length=200)),
                ('passenger', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
