# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-08 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
